apps/office/urls.py
from django.urls import path

from .views import office_menu, create_patient, patients_list, patient_details, client_office, client_xray, client_edit_data, xray_result, xray_history, request_history
from .views import incoming_requests, request_details, doctor_requests_history


urlpatterns = [
    path('', office_menu, name='office_menu'),
    path('create_patient/', create_patient, name='create_patient'),
    path('patients_list/', patients_list, name='patients_list'),
    path('patient/<str:iin>/', patient_details, name='patient_details'),
    path('requests/', incoming_requests, name='incoming_requests'),
    path('request/<int:pk>', request_details, name='request_details'),
    path('request/history', doctor_requests_history, name='doctor_request_history'),

    # Client side
    path('client/', client_office, name='client_office'),
    path('client/xray', client_xray, name='client_xray'),
    path('client/xray/history', xray_history, name='xray_history'),
    path('client/xray/result/<int:xray_pk>', xray_result, name='xray_result'),
    path('client/edit', client_edit_data, name='client_edit_data'),
    path('client/requests/', request_history, name='request_history'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.landing.urls')),
    path('profiles/', include('apps.profiles.urls')),
    path('office/', include('apps.office.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/office/models.py
import os

from django.db import models
from django.conf import settings

from apps.profiles.models import Profile
from .exceptions import ProfileNotDoctorException
from apps.xray_backend.backend import predict_pneumonia_result


class Patient(models.Model):
    GENDERS = (
        ('Male', 'Мужской'), 
        ('Female', 'Женский')
    )

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Аккаунт')
    first_name = models.CharField(max_length=255, blank=False, null=True, verbose_name='Имя')
    last_name = models.CharField(max_length=255, blank=False, null=True, verbose_name='Фамилия')
    iin = models.CharField(max_length=12, blank=False, null=True, verbose_name='ИИН', unique=True)
    email = models.EmailField(null=True, blank=True)
    phone_number = models.CharField(max_length=16, verbose_name='Номер телефона', blank=True, null=True, unique=True)
    gender = models.CharField(null=True, blank=False, verbose_name='Пол', choices=GENDERS, max_length=12)
    birth_date = models.DateField(verbose_name='Дата рождения', blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Пациент'
        verbose_name_plural = 'Пациенты'


class Diagnosis(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False, verbose_name='Название диагноза')
    description = models.TextField(verbose_name='Описание диагноза', null=True, blank=True)
    treatment = models.TextField(verbose_name='Способ лечения', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Диагноз'
        verbose_name_plural = 'Диагнозы'


class XRay(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, verbose_name='Пациент')
    photo = models.ImageField(upload_to='xrays/', verbose_name='Рентгеновский снимок')
    result = models.CharField(max_length=1024, null=True, blank=True, verbose_name='Результат')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.patient}: {self.created_at}'

    def save(self, *args, **kwargs):
        if not self.pk:
            # If instance is newly created

            # Пока отключил часть с машинным обучением
            # result = predict_pneumonia_result(os.path.join(settings.MEDIA_ROOT, 'xrays', os.path.basename(self.photo.name)))
            # if result == 0:
            #     self.result = "Нормальное"
            # else:
            #     self.result = "Пневмония"
            result = "Нормально"

        super(XRay, self).save(*args, **kwargs)

    def is_have_request(self):
        if XRayRequest.objects.filter(x_ray=self).exists():
            return True
        return False

    def get_request(self):
        if XRayRequest.objects.filter(x_ray=self).exists():
            return XRayRequest.objects.filter(x_ray=self).first()
        return None

    class Meta:
        verbose_name = 'Снимок пациента'
        verbose_name_plural = 'Снимки пациентов'


class XRayRequest(models.Model):
    x_ray = models.ForeignKey(XRay, on_delete=models.CASCADE, verbose_name='Рентгеновский снимок')
    doctor = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Доктор')
    diagnosis = models.ForeignKey(Diagnosis, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Диагноз')
    doctor_comment = models.TextField(verbose_name='Комментарий доктора', null=True, blank=True)
    is_answered = models.BooleanField(default=False, verbose_name='Отвечен ли доктором')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.x_ray}: {self.doctor}'

    class Meta:
        verbose_name = 'Заявка на рассмотрение доктора'
        verbose_name_plural = 'Заявки на рассмотрение доктора'

apps/office/forms.py
from django.forms import ModelForm, TextInput, DateTimeInput, HiddenInput, ModelChoiceField
from django.core.exceptions import ValidationError

from .models import Patient, XRay, XRayRequest
from .tools import iin_to_datetime
from .widgets import DatePickerInput

from apps.profiles.models import Profile


class PatientModelForm(ModelForm):
    class Meta:
        model = Patient
        fields = ('first_name', 'last_name', 'iin', 'birth_date', 'gender', 'email', 'phone_number')

        widgets = {
            'phone_number': TextInput(attrs={'id': 'phone-mask'}),
            'birth_date': DatePickerInput(),
        }

    def clean(self):
        cd = self.cleaned_data

        iin = cd.get('iin')
        birth_date = cd.get('birth_date')
        phone_number = cd.get('phone_number')

        # if Patient.objects.filter(iin=iin).exists():
        #     raise ValidationError("Пациент с таким ИИН уже существует")

        # if Patient.objects.filter(phone_number=phone_number).exists():
        #     raise ValidationError('Пациент с таким номером телефона уже существует')

        if not iin.isnumeric():
            raise ValidationError("ИИН должен содержать только цифры")   

        if not(iin_to_datetime(iin) == birth_date):
            raise ValidationError("ИИН и дата рождения должны совпадать")

        return cd


class XRayModelForm(ModelForm):
    class Meta:
        model = XRay
        fields = ('photo',)


class XRayRequestForm(ModelForm):
    class Meta:
        model = XRayRequest
        fields = ('doctor', )

    def __init__(self, *args, **kwargs):
        super(XRayRequestForm, self).__init__(*args, **kwargs)
        self.fields['doctor'] = ModelChoiceField(queryset=Profile.objects.filter(role=1), label='Доктор')


class XRayRequestDetailsForm(ModelForm):
    class Meta:
        model = XRayRequest
        fields = ('diagnosis', 'doctor_comment')

apps/office/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.http import Http404
from django.forms.models import model_to_dict
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import PatientModelForm, XRayModelForm, XRayRequestForm, XRayRequestDetailsForm
from .models import Patient, XRay, XRayRequest
from .decorators import doctor_required, client_required, confirmed_client_required


@login_required(login_url='/profiles/login/')
@doctor_required
def office_menu(request):
    return render(request, 'office/doctor/menu.html')


@login_required(login_url='/profiles/login/')
@doctor_required
def create_patient(request):
    form = PatientModelForm(request.POST or None, request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.info(request, 'Patient created')
        else:
            messages.error(request, 'Patient not created')

    return render(request, 'office/doctor/create_patient.html', {'patient_form': form})


@login_required(login_url='/profiles/login/')
@doctor_required
def patients_list(request):
    page_num = request.GET.get('page', 1)
    query = request.GET.get('patient_name', '')
    if query:
        if ' ' in query:
            first_name = query.split(' ')[0]
            last_name = query.split(' ')[1]
            patients = Patient.objects.filter(Q(first_name__icontains=first_name) | Q(last_name__icontains=last_name))
        else:
            patients = Patient.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query))
        
        paginator = Paginator(patients, 1)
        try:
            page_obj = paginator.page(page_num)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        return render(request, 'office/doctor/search_result.html',{'page_obj': page_obj})

    patients = Patient.objects.all()
    paginator = Paginator(patients, 1)
    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'office/doctor/patients_list.html', {'page_obj': page_obj})


@login_required(login_url='/profiles/login/')
@doctor_required
def doctor_requests_history(request):
    requests = XRayRequest.objects.filter(doctor=request.user, is_answered=True)
    return render(request, 'office/doctor/request_history.html', {'requests': requests})


@login_required(login_url='/profiles/login/')
@doctor_required
def patient_details(request, iin):
    patient = Patient.objects.filter(iin=iin).first()
    birth_date = patient.birth_date.strftime('%d.%m.%Y')

    if not patient:
        Http404()

    if request.method == 'POST':
        form = PatientModelForm(request.POST, instance=patient)
        if form.is_valid():
            form.save()
            messages.info(request, 'Patient edited')
        else:
            messages.error(request, 'Edition error')
    else:
        form = PatientModelForm(instance=patient)
    
    return render(request, 'office/doctor/patient_details.html', {'form': form,  'birth_date': birth_date, 'patient': patient })


@login_required(login_url='profiles/login/')
@doctor_required
def incoming_requests(request):
    requests = XRayRequest.objects.filter(doctor=request.user, is_answered=False)
    return render(request, 'office/doctor/incoming_requests.html', {'requests': requests})


@login_required(login_url='profiles/login/')
@doctor_required
def request_details(request, pk):
    if XRayRequest.objects.filter(pk=pk).exists():
        xray_request = XRayRequest.objects.filter(pk=pk).first()
        if request.method == 'POST':
            form = XRayRequestDetailsForm(data=request.POST)
            x_ray_request = form.save(commit=False)
            xray_request.is_answered = True
            xray_request.doctor = request.user
            xray_request.doctor_comment = x_ray_request.doctor_comment
            xray_request.diagnosis = x_ray_request.diagnosis
            xray_request.save()
            return render(request, 'office/doctor/request_details.html', {'xray_request': xray_request, 'form': form})
        else:
            form = XRayRequestDetailsForm()

        return render(request, 'office/doctor/request_details.html', {'xray_request': xray_request, 'form': form})
    raise Http404()


# Client side
@login_required(login_url='profiles/login')
@client_required
def client_office(request):
    return render(request, 'office/client/menu.html')


@login_required(login_url='profiles/login')
@client_required
def client_xray(request):
    if request.method == 'POST':
        form = XRayModelForm(files=request.FILES)
        if form.is_valid():
            if Patient.objects.filter(profile=request.user).exists():
                patient = Patient.objects.filter(profile=request.user).first()
                xray = form.save(commit=False)
                xray.patient = patient
                xray.save()
                return redirect('xray_result', xray_pk=xray.pk)

            return Http404()
    else:
        form = XRayModelForm()

    return render(request, 'office/client/xray.html', {'form': form})


@login_required(login_url='profiles/login')
@client_required
def xray_result(request, xray_pk):
    xray = XRay.objects.filter(pk=xray_pk).first()
    if request.method == 'POST':
        if not request.user.confirmed:
            raise Http404()

        form = XRayRequestForm(request.POST)
        if form.is_valid():
            xray_request = form.save(commit=False)
            xray_request.x_ray = xray
            xray_request.save()
            messages.success(request, 'Ваша заявка успешно отправлена доктору!')
        else:
            messages.error(request, 'Ошибка отправки заявки')

        return render(request, 'office/client/xray_result.html', {'xray': xray})

    form = XRayRequestForm()
    return render(request, 'office/client/xray_result.html', {'xray': xray, 'form': form})


@login_required(login_url='profiles/login')
@client_required
def xray_history(request):
    patient = Patient.objects.filter(profile=request.user).first()
    xrays = XRay.objects.filter(patient=patient).order_by('-created_at')
    return render(request, 'office/client/xray_history.html', {'xrays': xrays }) 
    


@login_required(login_url='profiles/login')
@client_required
def client_edit_data(request):
    patient = Patient.objects.filter(profile=request.user).first()
    if patient.birth_date:
        birth_date = patient.birth_date.strftime('%d.%m.%Y')
    else:
        birth_date = None

    if not patient:
        Http404()

    if request.method == 'POST':
        form = PatientModelForm(request.POST, instance=patient)
        if form.is_valid():
            form.save()
            messages.info(request, 'Patient edited')
        else:
            messages.error(request, 'Edition error')
    else:
        form = form = PatientModelForm(instance=patient)
    
    return render(request, 'office/client/edit_data.html', {'form': form,  'birth_date': birth_date, 'patient': patient })


@login_required(login_url='profiles/login')
@client_required
@confirmed_client_required
def request_history(request):
    requests = XRayRequest.objects.filter(x_ray__patient__profile=request.user)
    return render(request, 'office/client/request_history.html', {'requests': requests})

templates/office/doctor/create_patient.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}   

{% block title %}Создание пациента{% endblock %}

{% block content %}
<div class="container m-100">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{% url 'office_menu' %}">Кабинет</a></li>
          <li class="breadcrumb-item active">Создание пациента</li>
        </ol>
    </nav>
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO and message.message == 'Patient created' %}
                <div class="container">
                    <div class="alert alert-success" role="alert">
                        Пользователь успешно создан
                    </div>
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR and message.message == 'Patient not created' %}
                <div class="container">
                    <div class="alert alert-error" role="alert">
                       Неправильно введен ИИН или номер телефона
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
<h5>Звездочкой (*) отмечены обязательные для заполнения поля</h5>
<form method="POST">
    {% csrf_token %}
    {{ patient_form|crispy }}

    <button class="btn btn-success" type="submit">Создать пациента</button>
</form>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://unpkg.com/imask"></script>
<script src="{% static 'js/phone_mask.js' %}"></script>
<script>
    $(function () {
      $("#datetimepicker1").datetimepicker({
        format: 'DD/MM/YYYY HH:mm',
      });
    });
</script>
{% endblock %}

templates/office/doctor/incoming_requests.html
{% extends 'base.html' %}

{% block title %}Список пациентов{% endblock %}


{% block content %}
<div class="m-100 container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{% url 'office_menu' %}">Кабинет</a></li>
          <li class="breadcrumb-item active">Входящие заявки</li>
        </ol>
    </nav>
    <div class="row">
        {% if requests %}
            {% for r in requests %}
            <div class="col-sm-4 mb-5 text-center">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ r.x_ray.photo.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ r.x_ray.patient}}: {{ r.x_ray.result }}<br/>{{ r.doctor }}</h5>
                        <a href="{% url 'request_details' r.pk %}" class="btn btn-primary">Просмотреть</a>
                    </div>
                </div>    
            </div>
            {% endfor %}
        {% else %}
        <h2>Входящие заявки отсутсвуют</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/office/doctor/menu.html
{% extends 'base.html' %}

{% block title %}Меню кабинета{% endblock %}

{% block content %}
<div class="container office-menu mb-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
          <li class="breadcrumb-item active">Кабинет</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-sm text-center">
            <a href="{% url 'create_patient' %}" class="menu_btn">
                <i class="fa fa-user-plus fa-5x" aria-hidden="true"></i>
                <p>Создание пациента</p>
            </a>
        </div>
        <div class="col-sm text-center">
            <a href="{% url 'patients_list' %}" class="menu_btn">
                <i class="fa fa-list fa-5x" aria-hidden="true"></i>
                <p>Список пациентов</p>
            </a>
        </div>
        <div class="col-sm text-center">
            <a href="{% url 'incoming_requests' %}" class="menu_btn">
                <i class="fa fa-user-md fa-5x" aria-hidden="true"></i>
                <p>Входящие заявки</p>
            </a>
        </div>
        <div class="col-sm text-center">
            <a href="{% url 'doctor_request_history' %}" class="menu_btn">
                <i class="fa fa-archive fa-5x" aria-hidden="true"></i>
                <p>История заключений</p>
            </a>
        </div>
    </div>
</div>

{% endblock %}

templates/office/doctor/patient_details.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}  

{% block title %}Изменение данных пациента{% endblock %}

{% block content %}
<div class="m-100 container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{% url 'office_menu' %}">Кабинет</a></li>
          <li class="breadcrumb-item"><a href="{% url 'patients_list' %}">Список пациентов</a></li>
          <li class="breadcrumb-item active">{{ patient.first_name}} {{ patient.last_name }}</li>
        </ol>
    </nav>
    {% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO and message.message == 'Patient edited' %}
            <div class="container">
                <div class="alert alert-success" role="alert">
                    Данные пользователя успешно сохранены
                </div>
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR and message.message == 'Edition error' %}
            <div class="container">
                <div class="alert alert-error" role="alert">
                    Данные пользователя не изменены
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
    <div class="row">
        <div class="col-sm-6">
            <h5>Звездочкой (*) отмечены обязательные для заполнения поля</h5>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success" type="submit">Изменить данные</button>
            </form>
        </div>
        <div class="col-sm-6">
            <h5>Список диагнозов</h5>
            <ul class="list-group">
                <li class="list-group-item">Cras justo odio</li>
                <li class="list-group-item">Dapibus ac facilisis in</li>
                <li class="list-group-item">Morbi leo risus</li>
                <li class="list-group-item">Porta ac consectetur ac</li>
                <li class="list-group-item">Vestibulum at eros</li>
              </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://unpkg.com/imask"></script>
<script src="{% static 'js/phone_mask.js' %}"></script>
<script>
document.addEventListener("DOMContentLoaded", function(event) { 
    let time_input = document.querySelector('#id_birth_date')

    let birth_date = "{{birth_date}}"
    let year = birth_date.split('.')[2]
    let month = birth_date.split('.')[1]
    let day = birth_date.split('.')[0]

    let new_value = `${year}-${month}-${day}`
    time_input.setAttribute('value', new_value)

    let time_input_div = document.querySelector('#div_id_birth_date')

    time_input_div.innerHTML += `<p><b>Текущая дата рождения: {{birth_date}}</b></p>`
});
    
</script>
{% endblock %}

templates/office/doctor/patients_list.html
{% extends 'base.html' %}

{% block title %}Список пациентов{% endblock %}


{% block content %}
<div class="m-100 container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{% url 'office_menu' %}">Кабинет</a></li>
          <li class="breadcrumb-item active">Список пациентов</li>
        </ol>
    </nav>
    <form method="GET">
        <div class="row">
          <div class="col">
            <label for="search_field"><b>Поиск пациента</b></label>
            <input type="text" class="form-control" id="search_field" placeholder="Введите имя" required name="patient_name">
            <button class="btn btn-outline-secondary mt-2" type="submit">Искать</button>
          </div>
          <div class="col">
            
          </div>
        </div>
    </form>
    <div class="row">
        {% for patient in page_obj %}
        <div class="col-sm-6 mb-3 mt-3">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title">{{patient.first_name}} {{ patient.last_name }}</h5>
                <p class="card-text">
                    <b>ИИН:</b> {{patient.iin}}<br/>
                    <b>Пол:</b> {{patient.gender}}<br/>
                    <b>Дата рождения:</b> {{patient.birth_date}}<br/>
                    <b>Номер телефона:</b> {{patient.phone_number}}<br/>
                    <b>Email:</b> {{patient.email}}<br/>
                    <b>Дата добавления пациента:</b> {{patient.created_at}}
                </p>
                <a href="{% url 'patient_details' patient.iin %}" class="btn btn-primary patient-view-btn">Просмотр</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><b><<</b></a></li>
            {% if page_obj.number > 3 %}
                <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            {% if page_obj.number > 4 %}
                <li class="page-item"><a class="page-link">...</a></li>
            {% endif %}
            {% endif %}
            {% endif %}
    
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item disabled"><a class="page-link" href="?page={{ num }}" style="color:black;">{{ num }}</a></li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item "><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
    
            {% if page_obj.has_next %}
                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    <li class="page-item"><a class="page-link">...</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><b>>></b></a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

templates/office/doctor/request_details.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Заявка{% endblock %}

{% block content %}
<div class="container office-menu mb-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{% url 'client_office' %}">Кабинет</a></li>
          <li class="breadcrumb-item"><a href="{% url 'incoming_requests' %}">Входящие заявки</a></li>
          <li class="breadcrumb-item active">Заявка</li>
        </ol>
    </nav>
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="container">
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="container">
                    <div class="alert alert-error" role="alert">
                       {{ message }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="row">
      <div class="col-sm">
        <h4>{{ xray_request.x_ray.patient }}: {{ xray_request.x_ray.result }}</h4>
        <img class="img-fluid" src="{{ xray_request.x_ray.photo.url }}" alt="">
        {% if not xray_request.is_answered %}
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Ответить</button>
            </form>
        {% else %}
            {% if xray_request.diagnosis %}
            <h4>Диагноз: {{ xray_request.diagnosis }}</h4>
            {% endif %}
            {% if xray_request.doctor_comment %}
            <h4>Комментарий: {{ xray_request.doctor_comment }}</h4>
            {% endif %}
        {% endif %}
      </div>
    </div>
</div>
{% endblock %}

templates/office/doctor/request_history.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}История заявок{% endblock %}

{% block content %}
<div class="container office-menu mb-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{% url 'client_office' %}">Кабинет</a></li>
          <li class="breadcrumb-item active">История заключений</li>
        </ol>
    </nav>
    <div class="row text-center">
    {% if requests %}
      {% for r in requests %}
        <div class="col-sm-4 mb-5 text-center">
          <div class="card" style="width: 18rem;">
              <img class="card-img-top" src="{{ r.x_ray.photo.url }}" alt="Card image cap">
              <div class="card-body">
                  <h5 class="card-title">{{ r.x_ray.patient}}: {{ r.x_ray.result }}<br/>{{ r.doctor }}</h5>
                  {% if r.is_answered %}
                      <a href="{% url 'request_details' r.pk %}" class="btn btn-primary">Просмотреть</a>
                  {% else %}
                      <p>Не отвечено</p>
                  {% endif %}
              </div>
          </div>    
        </div>
      {% endfor %}
    {% else %}
        <h4>Заключений нет</h4>
    {% endif %}
    </div>
</div>

{% endblock %}